// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5F0mZINZCRYFxg6SCctTa0Yl7FIOxf_4',
    appId: '1:952983237872:web:11bce99b73f70f9a8f7e35',
    messagingSenderId: '952983237872',
    projectId: 'nav-stock-analysis-app-16f6d',
    authDomain: 'nav-stock-analysis-app-16f6d.firebaseapp.com',
    storageBucket: 'nav-stock-analysis-app-16f6d.firebasestorage.app',
    measurementId: 'G-QPK25SNPTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5F0mZINZCRYFxg6SCctTa0Yl7FIOxf_4',
    appId: '1:952983237872:android:ae44bad5821cf3498f7e35',
    messagingSenderId: '952983237872',
    projectId: 'nav-stock-analysis-app-16f6d',
    storageBucket: 'nav-stock-analysis-app-16f6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5F0mZINZCRYFxg6SCctTa0Yl7FIOxf_4',
    appId: '1:952983237872:ios:placeholder',
    messagingSenderId: '952983237872',
    projectId: 'nav-stock-analysis-app-16f6d',
    storageBucket: 'nav-stock-analysis-app-16f6d.firebasestorage.app',
    iosBundleId: 'com.example.stockApp',
  );
}
